language: php
sudo : false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer selfupdate
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover coverage.clover tests
  - if [[ 'php --version' != *7* ]]; then ./bin/clover-to-html cloverToHtml:convert coverage.clover coverage; fi;
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ 'php --version' != *7* ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
